services:
  root:
    image: node:16.14-slim
    working_dir: /app
    command:
      - sh
      - -c
      - |
        npm install
    volumes:
      - .:/app:cached
  db:
    image: postgres:17.0
    restart: always
    shm_size: 128mb
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  backend:
    image: node:22.13.1
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app/backend:cached
    user: "1000"
    command:
      - sh
      - -c
      - |
        apt install procps
        cd backend
        npm i
        npm run start:dev
    ports:
      - 3000:3000
  scheduler:
    image: node:22.13.1
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    working_dir: /app
    volumes:
      - ./scheduler:/app/scheduler:cached
    command:
      - sh
      - -c
      - |
        cd scheduler
        npm i
        npm run start:dev
    ports:
      - 3001:3001
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch_540
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
