database:
  port: 5432
  host: db
  username: postgres
  password: postgres
  type: "postgres"
  database: "postgres"
mailerConfig:
  host: 'smtp.mail.ru'
  user: 'toontown@bk.ru'
  password: 'tsS2gxj4mtLHQwVuNE7u'
timeLifeAuthCode: время жизни кода авторизации в минутах
accessSecret: секретный ключ
timeLifeAccessToken: время жизни токена авторизации в минутах
timeLifeRefreshToken: время жизни refresh токена в минутах
