database:
  port: 5432
  host: db
  username: postgres
  password: postgres
  type: "postgres"
  database: "postgres"
timeLifeAuthCode: время жизни кода авторизации в минутах
accessSecret: секретный ключ
timeLifeAccessToken: время жизни токена авторизации в минутах
timeLifeRefreshToken: время жизни refresh токена в минутах
elasticSearch:
  url: 'http://elastic:9200'
  maxRetries: 10
  requestTimeout: 60000
  pingTimeout: 60000
  sniffOnStart: true
  auth:
    userName: elastic
    password: elastic
  keys:
    - key: common
      name: common
keysForIncomingRequests:
  url: 'http://mailing:3001/api'
  audience: mailing
  keys:
    - issuer: backend
      secret: stub
      algorithm: HS256
